name: Snapshot

on: [repository_dispatch]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    if: github.event.action == 'snapshot'

    steps:
      - name: Check ref
        run: test -n ${{ github.event.client_payload.ref }} || (echo "Missing ref" && exit 1)

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Check version
        run: test -n ${{ github.event.client_payload.version }} || (echo "Missing snapshot version" && exit 1)

      - name: Build image
        run: docker build -t banzaicloud/pipeline:${{ github.event.client_payload.version }} --build-arg VERSION=${{ github.event.client_payload.version }} .

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push banzaicloud/pipeline:${{ github.event.client_payload.version }}
